# action.yml
name: 'Echo Value - Docker'
description: 'Echo the explicitly passed value via a Docker action'
branding:
  icon: anchor
  color: yellow

runs:
  using: 'docker'
  image: Dockerfile
  env:
    VALUE: bar