# action.yml
name: 'Echo Value - Composite'
description: 'Echo the explicitly passed value via a Composite action'
branding:
  icon: anchor
  color: yellow

runs:
  using: 'composite'
  steps:
    - id: echo-value
      shell: sh
      run: |
        echo "Composite action says: ${VALUE}"
      env:
        VALUE: bar
