name: demo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: export an environment variable
        uses: ./.github/actions/export-value
        with:
          value: foo
      - name: Echo the explicitly passed value
        uses: ./.github/actions/echo-value
        with:
          value: bar